# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title:  小码张
subtitle: 静待人生
name: 小码张 
email: 964999525@qq.com
description: 技术分享。
keywords: Spring,Spring Boot,Spring Cloud,开发者,IT技术博客,Java,
encoding: "utf-8"
favicon: favicon.ico 

repository: zhangtiezhi/zhangtiezhi.github.io
github_url: https://github.com/zhangtiezhi
url: https://zhangtiezhi.github.io
enforce_ssl: ishuo520.club

## Gem
plugins:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata
  - jekyll-octicons
  
# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true
  syntax_highlighter: rouge

syntax_highlighter_opts:
   coderay_line_numbers:  nil

# Pagination
paginate: 12
paginate_path: 'page:num'

# Navigation. top menu list
menus:


  -
    href: /arch.html
    label: 架构
    target: _self

  -
    href: /link.html
    label: 友链
    target: _self



# Navigation. main menu list
navs:

  -
    href: /
    label: Home

  -
    href: /spring-boot.html
    label: Spring Boot
    target: _self
    subnav:

      -
        subHref: /spring-boot.html
        subLabel: Spring Boot

      -
        subHref: /spring-cloud.html
        subLabel: Spring Cloud

  -
    href: /about.html
    label: About
    target: _self


# labels. my blog key words
labels:

  -
    href: /it.html
    label: IT 
    target: _blank



# selected articles
classes:

  -
    href: /life.html
    name: 我的故事
    describe: 生活就是故事，故事就是生活

  -
    href: /arch.html
    name: 架构师之路
    describe: 一个架构师的自我修养



# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# Sidebar to show popular repo
side_bar_repo_limit: 6 # Number of repos to show

# Google Analytics
# analytics :
# provider : google
#   google :
#     tracking_id : ''  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, MySQL, Oracle, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, NodeJS, ExpressJS, MongoDB, Redis, PHP,  Boostrap]
skill_mobile_app_keywords: [vuejs, hyhird app]


# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: zhangtiezhi
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: zhangtiezhi
    repo: zhangtiezhi.github.io
    oauth:
        client_id: 848f22830b1ff83d8a03
        client_secret: 9c633a2ee2d4e454ae7a77f12ae2c3f6949eb9a4
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: zhangtiezhi
    repo: zhangtiezhi.github.io
    clientID: 848f22830b1ff83d8a03
    clientSecret: 9c633a2ee2d4e454ae7a77f12ae2c3f6949eb9a4
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : true
